query getMyRestaurants {
  myRestaurants {
    ok
    error
    restaurants {
      id
      name
      coverImg
      address
      deliveryCost
      deliveryTime
      minimalOrder
      category {
        name
        slug
      }
    }
  }
}
